-- =============================================
-- Vehicle Reviews Enhancement
-- Creates a review table for vehicle reviews
-- =============================================

-- Create the review table
CREATE TABLE IF NOT EXISTS public.review (
    review_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_text TEXT NOT NULL,
    review_rating INT NOT NULL CHECK (review_rating BETWEEN 1 AND 5),
    review_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    inv_id INT NOT NULL REFERENCES public.inventory(inv_id) ON DELETE CASCADE,
    account_id INT NOT NULL REFERENCES public.account(account_id) ON DELETE CASCADE,
    UNIQUE(inv_id, account_id) -- One review per user per vehicle
);

-- Create indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_review_inv_id ON public.review(inv_id);
CREATE INDEX IF NOT EXISTS idx_review_account_id ON public.review(account_id);
